---
host: localhost
port: 9999

elasticSearch:
  defaultType: project
  index: app-test
  host: localhost
  port: 9200
  keepAlive: false


pretty: true
defaultLimit: 20
hardLimit: 100

proxy: {}
static: {}
types: {}

