grammkit = require('grammkit')
parse = require('pegjs/lib/parser').parse
content = ''
process.stdin.resume()
process.stdin.on 'data', (buf) ->
  content += buf.toString()
process.stdin.on 'end', ->
  grammar = parse(content)
  console.log """
  <!DOCTYPE html>
  <html>
  <head>
    <style>
    svg {
      fill:none;
      stroke: black;
      font-size: 10pt;
      font-family: sans;
      text-anchor: middle;
    }
    rect {
      fill:#e9e0b4;
      stroke:black;
    }
    </style>
  </head>
  <body><dl>
  """
  grammar.rules.forEach (rule) ->
    console.log "<dt>#{rule.name}:</dt><dd>"
    process.stdout.write grammkit.diagram(rule)
    console.log '</dd>'
  console.log '</dl></body></html>'

# ---
# generated by js2coffee 2.2.0
