module.exports =
  isTerm:(t)->Array.isArray(t) and typeof t[0] is "string"
  MUST:"MUST"
  MUST_NOT:"MUST_NOT"
  SHOULD:"SHOULD"
  QLF:"QLF"
  SEQ:"SEQ"
  OR:"OR"
  AND:"AND"
  NOT:"NOT"
  TERM:"TERM"
  DQUOT:"DQUOT"
  SQUOT:"SQUOT"
  VAR:"VAR"
  VARS:"VARS"
  NOP:"NOP"
