module.exports =
  DomainObject: require "./config-types/domainobject"
  FullText: require "./config-types/fulltext"
  ByField: require "./config-types/by-field"
  ByRelevance: require "./config-types/by-relevance"
  GeoLocation: require "./config-types/geolocation"
  Prefix: require "./config-types/prefix"
  Simple: require "./config-types/simple"
  Attribute: require "./config-types/attribute"
  ConfigBuilder: require  "./config-builder"
  Cli: require "./cli"
  Server: require "./server"
  defaults: require "../default-settings"
  ConfigNode: require "./config-node"
